name: Run Gradle on PRs
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Gradle CI
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: ci
          build-root-directory: backend/
          wrapper-directory: backend/
        id: gradle
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        if: failure()
        with:
          message: Build failed ${{ steps.gradle.outputs.build-scan-url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
