name: Run Gradle on PRs
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: Set up 
      uses: actions/checkout@master
      with:
        working-directory: ./backend/
    - name: Gradle build and check
      uses: MrRamych/gradle-actions/openjdk-12@3.1
      with:
        working-directory: ./backend/
        args: build check
