name: Run Gradle on PRs
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: MrRamych/gradle-actions/openjdk-12@3.1
      with:
        args: build check
